"""Merge existing data/ + spec-extraction output + curated layer.

Inputs (any of which may be absent):
    data/nodes.csv, data/edges.csv, data/rel19_text_chunks.jsonl  (existing)
    data/_intermediate/spec_nodes.csv, spec_edges.csv, spec_chunks.jsonl  (from ingest_specs.py)
    data/_intermediate/curated_nodes.csv, curated_edges.csv, curated_chunks.jsonl  (from build_curated_layer.py)

Output (overwritten in place):
    data/nodes.csv
    data/edges.csv
    data/rel19_text_chunks.jsonl
    data/rel19_3gpp_telecom_kg.graphml

Dedup rules:
    Nodes: primary key = entity_id. On conflict, the existing node wins and
        the duplicate is dropped. The existing description is preserved
        unless the existing description is empty, in which case the new one
        fills it.
    Edges: primary key = (source_id, target_id, relation_type). Duplicates dropped.
    Chunks: primary key = chunk_id. Duplicates dropped; first-seen wins.

After writing the CSVs and JSONL, a fresh GraphML is generated by writing
nodes (entity_id as id, entity_type as a type attribute) and edges from the
merged edges CSV.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

import networkx as nx

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = REPO_ROOT / "data"
INTERMEDIATE_DIR = DATA_DIR / "_intermediate"

NODE_COLUMNS = [
    "entity_id", "entity_type", "description", "chunk_ids", "source_files",
    "release", "created_at", "file_path", "source_id", "raw_entity_id",
]
EDGE_COLUMNS = [
    "source_id", "target_id", "relation_type", "weight", "description",
    "keywords", "source_id_edge", "file_path", "created_at", "source_file", "release",
]


def read_csv_rows(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def read_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    out: list[dict] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return out


def merge_nodes(existing: list[dict], new: list[dict]) -> tuple[list[dict], int]:
    by_id: dict[str, dict] = {}
    for n in existing:
        by_id[n["entity_id"]] = dict(n)
    added = 0
    for n in new:
        if n["entity_id"] in by_id:
            cur = by_id[n["entity_id"]]
            if not cur.get("description", "").strip() and n.get("description", "").strip():
                cur["description"] = n["description"]
                by_id[n["entity_id"]] = cur
            continue
        by_id[n["entity_id"]] = dict(n)
        added += 1
    return list(by_id.values()), added


def merge_edges(existing: list[dict], new: list[dict]) -> tuple[list[dict], int]:
    seen: set[tuple[str, str, str]] = set()
    out: list[dict] = []
    for e in existing:
        k = (e["source_id"], e["target_id"], e["relation_type"])
        if k in seen:
            continue
        seen.add(k)
        out.append(dict(e))
    added = 0
    for e in new:
        k = (e["source_id"], e["target_id"], e["relation_type"])
        if k in seen:
            continue
        seen.add(k)
        out.append(dict(e))
        added += 1
    return out, added


def merge_chunks(existing: list[dict], new: list[dict]) -> tuple[list[dict], int]:
    """Concatenate. We do not dedup across the existing corpus because the
    original 896k-chunk JSONL contains 80x duplication of the same ~11k unique
    chunk_ids, and the TextRetriever iterates all chunks in order so dedup is
    not required for correctness. New chunks are de-duplicated against each
    other only.
    """
    seen: set[str] = set()
    new_unique: list[dict] = []
    added = 0
    for c in new:
        cid = c.get("chunk_id") or c.get("id") or ""
        if cid and cid in seen:
            continue
        if cid:
            seen.add(cid)
        new_unique.append(c)
        added += 1
    return list(existing) + new_unique, added


def write_csv(rows: list[dict], path: Path, columns: list[str]) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=columns)
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in columns})


def write_jsonl(rows: list[dict], path: Path) -> None:
    with path.open("w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


def build_graphml(nodes: list[dict], edges: list[dict]) -> nx.MultiDiGraph:
    G = nx.MultiDiGraph()
    for n in nodes:
        attrs = {k: v for k, v in n.items() if k != "entity_id"}
        G.add_node(n["entity_id"], **{k: ("" if v is None else v) for k, v in attrs.items()})
    for e in edges:
        attrs = {k: v for k, v in e.items() if k not in ("source_id", "target_id")}
        G.add_edge(e["source_id"], e["target_id"], **{k: ("" if v is None else v) for k, v in attrs.items()})
    return G


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--intermediate-dir", type=Path, default=INTERMEDIATE_DIR)
    p.add_argument("--data-dir", type=Path, default=DATA_DIR)
    args = p.parse_args()

    print("Loading existing data/ artifacts ...")
    existing_nodes = read_csv_rows(args.data_dir / "nodes.csv")
    existing_edges = read_csv_rows(args.data_dir / "edges.csv")
    existing_chunks = read_jsonl(args.data_dir / "rel19_text_chunks.jsonl")
    print(f"  existing: {len(existing_nodes)} nodes, {len(existing_edges)} edges, "
          f"{len(existing_chunks)} chunks")

    spec_nodes = read_csv_rows(args.intermediate_dir / "spec_nodes.csv")
    spec_edges = read_csv_rows(args.intermediate_dir / "spec_edges.csv")
    spec_chunks_raw = read_jsonl(args.intermediate_dir / "spec_chunks.jsonl")
    spec_chunks = [{"chunk_id": c.get("chunk_id", ""),
                    "text": c.get("text", ""),
                    "source_file": c.get("source_file", ""),
                    "release": c.get("release", "Rel-19")} for c in spec_chunks_raw]

    cur_nodes = read_csv_rows(args.intermediate_dir / "curated_nodes.csv")
    cur_edges = read_csv_rows(args.intermediate_dir / "curated_edges.csv")
    cur_chunks_raw = read_jsonl(args.intermediate_dir / "curated_chunks.jsonl")
    cur_chunks = [{"chunk_id": c.get("chunk_id", ""),
                   "text": c.get("text", ""),
                   "source_file": c.get("source_file", ""),
                   "release": c.get("release", "Rel-19")} for c in cur_chunks_raw]

    print(f"  spec layer:    {len(spec_nodes)} nodes, {len(spec_edges)} edges, {len(spec_chunks)} chunks")
    print(f"  curated layer: {len(cur_nodes)} nodes, {len(cur_edges)} edges, {len(cur_chunks)} chunks")

    new_nodes = spec_nodes + cur_nodes
    new_edges = spec_edges + cur_edges
    new_chunks = spec_chunks + cur_chunks

    print("Merging ...")
    nodes, added_n = merge_nodes(existing_nodes, new_nodes)
    edges, added_e = merge_edges(existing_edges, new_edges)
    chunks, added_c = merge_chunks(existing_chunks, new_chunks)
    print(f"  added: {added_n} nodes, {added_e} edges, {added_c} chunks")
    print(f"  merged totals: {len(nodes)} nodes, {len(edges)} edges, {len(chunks)} chunks")

    print("Writing data/nodes.csv, data/edges.csv, data/rel19_text_chunks.jsonl ...")
    write_csv(nodes, args.data_dir / "nodes.csv", NODE_COLUMNS)
    write_csv(edges, args.data_dir / "edges.csv", EDGE_COLUMNS)
    write_jsonl(chunks, args.data_dir / "rel19_text_chunks.jsonl")

    print("Building data/rel19_3gpp_telecom_kg.graphml ...")
    G = build_graphml(nodes, edges)
    nx.write_graphml(G, args.data_dir / "rel19_3gpp_telecom_kg.graphml")
    print(f"  wrote GraphML with {G.number_of_nodes()} nodes, {G.number_of_edges()} edges")

    feature_nodes = [n for n in nodes if n["entity_id"].startswith("FEATURE_")]
    print(f"  FEATURE_* nodes in final graph: {len(feature_nodes)}")
    for fn in feature_nodes[:5]:
        print(f"    - {fn['entity_id']} ({fn.get('entity_type', 'Concept')})")
    if len(feature_nodes) > 5:
        print(f"    ... and {len(feature_nodes) - 5} more")

    return 0


if __name__ == "__main__":
    sys.exit(main())